!!dev.wuffs.squatgrow.config.SquatGrowConfig
ae2Multiplier: 4
allowAdventureTwerking: true
chance: 0.5
debug: false
enableAE2Accelerator: true
enableDirtToGrass: true
enableMysticalCrops: true
hoeTakesDamage: false
ignoreList: ['minecraft:oak_sapling', 'minecraft:spruce_sapling', 'minecraft:birch_sapling',
  'minecraft:jungle_sapling', 'minecraft:acacia_sapling', 'minecraft:dark_oak_sapling',
  'minecraft:cherry_sapling', 'thermal:rubberwood_sapling']
randomTickMultiplier: 4
range: 3
requireHoe: false
requirements:
  durabilityDamage: 1
  enabled: true
  equipmentRequirement: {}
  heldItemRequirement: []
  requiredEnchantment: ''
  requiredItemTakesDamage: false
sugarcaneMultiplier: 4
useWhitelist: true
